### ISSUE TITLE
"No module named cgi"

### ISSUE THREAD

**Issue by paulftw** [rodaebel/boboongae#4]
dev_appserver throws an exception.

Steps to reproduce (tried on mac os):
cd /tmp/
virtualenv --no-site-packages bobo
cd bobo/
source bin/activate
git clone git://github.com/rodaebel/boboongae.git
cd boboongae/
python2.5 bootstrap.py --distribute && python2.5 bin/buildout
bin/dev_appserver parts/boboongae/

Then open localhost:8080 in browser:

WARNING  2011-06-13 13:14:57,943 urlfetch_stub.py:108] No ssl package found. urlfetch will not be able to validate SSL certificates.
INFO     2011-06-13 13:14:58,341 appengine_rpc.py:159] Server: appengine.google.com
INFO     2011-06-13 13:14:58,348 appcfg.py:440] Checking for updates to the SDK.
INFO     2011-06-13 13:14:59,653 appcfg.py:457] The SDK is up to date.
WARNING  2011-06-13 13:14:59,653 datastore_file_stub.py:657] Could not read datastore data from /private/tmp/bobo/boboongae/var/dev_appserver.datastore
INFO     2011-06-13 13:14:59,655 rdbms_sqlite.py:58] Connecting to SQLite database '' with file '/private/tmp/bobo/boboongae/var/dev_appserver.rdbms'
WARNING  2011-06-13 13:14:59,664 dev_appserver.py:4598] Could not initialize images API; you are likely missing the Python "PIL" module. ImportError: No module named _imaging
INFO     2011-06-13 13:14:59,670 dev_appserver_multiprocess.py:637] Running application boboongae on port 8080: http://localhost:8080
WARNING  2011-06-13 13:16:39,680 py_zipimport.py:139] Can't open zipfile /private/tmp/bobo/lib/python2.5/site-packages/setuptools-0.6c11-py2.5.egg: IOError: [Errno 13] file not accessible: '/private/tmp/bobo/lib/python2.5/site-packages/setuptools-0.6c11-py2.5.egg'
ERROR    2011-06-13 13:16:39,699 dev_appserver.py:4104] Exception encountered handling request
Traceback (most recent call last):
  File "/private/tmp/bobo/boboongae/parts/google_appengine/google/appengine/tools/dev_appserver.py", line 4053, in _HandleRequest
    self._Dispatch(dispatcher, self.rfile, outfile, env_dict)
  File "/private/tmp/bobo/boboongae/parts/google_appengine/google/appengine/tools/dev_appserver.py", line 3977, in _Dispatch
    base_env_dict=env_dict)
  File "/private/tmp/bobo/boboongae/parts/google_appengine/google/appengine/tools/dev_appserver.py", line 588, in Dispatch
    base_env_dict=base_env_dict)
  File "/private/tmp/bobo/boboongae/parts/google_appengine/google/appengine/tools/dev_appserver.py", line 3050, in Dispatch
    self._module_dict)
  File "/private/tmp/bobo/boboongae/parts/google_appengine/google/appengine/tools/dev_appserver.py", line 2954, in ExecuteCGI
    reset_modules = exec_script(handler_path, cgi_path, hook)
  File "/private/tmp/bobo/boboongae/parts/google_appengine/google/appengine/tools/dev_appserver.py", line 2834, in ExecuteOrImportScript
    exec module_code in script_module.__dict__
  File "/private/tmp/bobo/boboongae/parts/boboongae/main.py", line 3, in <module>
    from bobo import Application
  File "/private/tmp/bobo/boboongae/parts/google_appengine/google/appengine/tools/dev_appserver.py", line 1505, in Decorate
    return func(self, _args, *_kwargs)
  File "/private/tmp/bobo/boboongae/parts/google_appengine/google/appengine/tools/dev_appserver.py", line 2450, in load_module
    return self.FindAndLoadModule(submodule, fullname, search_path)
  File "/private/tmp/bobo/boboongae/parts/google_appengine/google/appengine/tools/dev_appserver.py", line 1505, in Decorate
    return func(self, _args, *_kwargs)
  File "/private/tmp/bobo/boboongae/parts/google_appengine/google/appengine/tools/dev_appserver.py", line 2339, in FindAndLoadModule
    description)
  File "/private/tmp/bobo/boboongae/parts/google_appengine/google/appengine/tools/dev_appserver.py", line 1505, in Decorate
    return func(self, _args, *_kwargs)
  File "/private/tmp/bobo/boboongae/parts/google_appengine/google/appengine/tools/dev_appserver.py", line 2282, in LoadModuleRestricted
    description)
  File "/private/tmp/bobo/boboongae/parts/boboongae/bobo.py", line 39, in <module>
    import webob
  File "/private/tmp/bobo/boboongae/parts/google_appengine/google/appengine/tools/dev_appserver.py", line 1505, in Decorate
    return func(self, _args, *_kwargs)
  File "/private/tmp/bobo/boboongae/parts/google_appengine/google/appengine/tools/dev_appserver.py", line 2450, in load_module
    return self.FindAndLoadModule(submodule, fullname, search_path)
  File "/private/tmp/bobo/boboongae/parts/google_appengine/google/appengine/tools/dev_appserver.py", line 1505, in Decorate
    return func(self, _args, *_kwargs)
  File "/private/tmp/bobo/boboongae/parts/google_appengine/google/appengine/tools/dev_appserver.py", line 2339, in FindAndLoadModule
    description)
  File "/private/tmp/bobo/boboongae/parts/google_appengine/google/appengine/tools/dev_appserver.py", line 1505, in Decorate
    return func(self, _args, *_kwargs)
  File "/private/tmp/bobo/boboongae/parts/google_appengine/google/appengine/tools/dev_appserver.py", line 2282, in LoadModuleRestricted
    description)
  File "/private/tmp/bobo/boboongae/parts/google_appengine/lib/webob/webob/**init**.py", line 3, in <module>
    import cgi
ImportError: No module named cgi

**Comment by rodaebel** [comment]
Thanks for reporting this and for providing the information to reproduce the issue. Unfortunately, the development appserver messes up sys.path which causes lots of problems within a virtualenv. The best workaround is not using virtualenv and the system Python at all. That's why I've installed a vanilla Python from python.org in ~/local/ for all GAE related tasks.

**Comment by paulftw** [comment]
Thanks for explaining that - I'm just learning how things work in python.
I've googled a patch to dev_appserver that seems to have fixed the issue.
http://code.google.com/p/googleappengine/issues/detail?id=4339

Now localhost:8080 displays "Bobo on Google App Engine". Closing the issue.

**Comment by rodaebel** [comment]
@paulftw: Thanks so much for the hint! My rod.recipe.appengine provides a buildout option for automatically patching the SDK. I've already committed the patch to boboongae. See http://github.com/rodaebel/boboongae/commit/b0d8de714bcc3623e909f389924274faa68f02a1 for further details. Makes things much easier.
